### ISSUE TITLE
Resnet for tf and when does the pytorch model come up?

### ISSUE THREAD

**Issue by EOLab** [DingXiaoH/Centripetal-SGD#5]
Hi thanks for the great repo

Could you please upload the resnet model and its setups?

And may I ask when the pytorch code will be available?

Thx in advance

**Comment by RohitKeshari** [comment]
+1, I am also interested in pytorch implementation

**Comment by DingXiaoH** [comment]
Thank you for being interested in this project. I am a little busy these days. I think I will have time for the pytorch codes if my experiments for my next paper fail so that I will not be busy working for my CVPR-2020 paper (lol).

**Comment by DingXiaoH** [comment]
Done.
